# Generated by Django 5.0.4 on 2024-04-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('key', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('long_url', models.CharField(max_length=512)),
                ('short_url', models.CharField(max_length=256)),
            ],
        ),
    ]
